### ISSUE TITLE
Change header values

### ISSUE THREAD

**Issue by SpaceboyRoss01** [adelphes/elf-tools#1]
I'm wanting to change the header values but I've found that's a bit hard.

**Comment by adelphes** [comment]
OK - what header values would you want to change?

**Comment by SpaceboyRoss01** [comment]
All of the values except for the offsets, elf version, and elf magic.

**Comment by adelphes** [comment]
I've merged in some changes to allow an `elf_header` object to be passed in the options to `build()`, allowing you to customise some of the fields. Does this match what you need?

**Comment by SpaceboyRoss01** [comment]
Yeah, it does. Thanks
